### ISSUE TITLE
内存占用过于巨大

### ISSUE THREAD

**Issue by Schwarzkopf-Henkal** [CodeforcesContestHelper/CodeforcesContestHelper#37]
如题，本人系统Win10 Enterprise 19042.804，该程序运行时内存占用超过1.6个G，且启动缓慢，堵塞其他程序。

可以提供更详细系统信息。

![](https://cdn-warfare-1302619124.file.myqcloud.com/qtniuo1l.png)

**Comment by tiger2005** [comment]
NW.js 本身的特性。如果可以的话请暂时使用网页端或者使用 Electron 进行封装。我们会在之后想办法解决。

**Comment by qinyihao** [comment]
NW.js的确是比较占用内存的，但是好像看到您电脑配置的内存应该是2gb的吧（

这个内存的量还是有点过小了，先请您使用网页版吧

**Comment by Schwarzkopf-Henkal** [comment]
> NW.js的确是比较占用内存的，但是好像看到您电脑配置的内存应该是2gb的吧（
> 
> 这个内存的量还是有点过小了，先请您使用网页版吧

我电脑内存8个G，光这个图上加起来就不止2G了

**Comment by qinyihao** [comment]
> > NW.js的确是比较占用内存的，但是好像看到您电脑配置的内存应该是2gb的吧（
> > 这个内存的量还是有点过小了，先请您使用网页版吧
> 
> 我电脑内存8个G，光这个图上加起来就不止2G了

您现在可以看一下release里面的exe，可能会好一点。
