### ISSUE TITLE
程序窗口

### ISSUE THREAD

**Issue by Schwarzkopf-Henkal** [CodeforcesContestHelper/CodeforcesContestHelper#38]
窗口有滚动条，且貌似窗口大小无法随着内容的折叠和展开而改变。是下载的最新一个Release的.exe文件

![](https://cdn-warfare-1302619124.file.myqcloud.com/xvoudksz.png)

**Comment by Schwarzkopf-Henkal** [comment]
哦，貌似这是个远古版本，那没事了。。。

**Comment by tiger2005** [comment]
啊这
